boot.o: boot.S multiboot.h x86_desc.h types.h
idtfunctions_asm.o: idtfunctions_asm.S
paging_asm.o: paging_asm.S paging.h
system_call_asm.o: system_call_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c exceptions.h types.h lib.h system_calls.h \
  file_system.h rtc.h keyboard.h paging.h x86_desc.h system_call_asm.h \
  terminal.h
file_system.o: file_system.c file_system.h rtc.h types.h lib.h keyboard.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_init.o: idt_init.c idt_init.h idtfunctions_asm.h exceptions.h types.h \
  lib.h system_calls.h file_system.h rtc.h keyboard.h paging.h x86_desc.h \
  system_call_asm.h terminal.h pit.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h rtc.h keyboard.h paging.h file_system.h system_call_asm.h \
  system_calls.h terminal.h pit.h
keyboard.o: keyboard.c keyboard.h types.h lib.h system_calls.h \
  file_system.h rtc.h paging.h x86_desc.h system_call_asm.h terminal.h \
  i8259.h
lib.o: lib.c lib.h types.h terminal.h system_calls.h file_system.h rtc.h \
  keyboard.h paging.h x86_desc.h system_call_asm.h
paging.o: paging.c paging.h x86_desc.h types.h
pit.o: pit.c pit.h i8259.h types.h lib.h terminal.h system_calls.h \
  file_system.h rtc.h keyboard.h paging.h x86_desc.h system_call_asm.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h terminal.h system_calls.h \
  file_system.h keyboard.h paging.h x86_desc.h system_call_asm.h
system_calls.o: system_calls.c system_calls.h file_system.h rtc.h types.h \
  lib.h keyboard.h paging.h x86_desc.h system_call_asm.h terminal.h
terminal.o: terminal.c terminal.h types.h lib.h system_calls.h \
  file_system.h rtc.h keyboard.h paging.h x86_desc.h system_call_asm.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h file_system.h rtc.h \
  keyboard.h system_calls.h paging.h system_call_asm.h terminal.h
